SuffolkLITLab/docassemble-ALDashboard

docassemble/ALDashboard/data/questions/validate_translation.yml

Addresses #4, catch other undesired translation typos that would not cause an error.
* Indented heading
* % with no space after
* missing opening or closing brackets
* missing opening or closing parens
* missing plain quotes (`"`)
* too many spaces after a %

Re: #4, catching translation typos

---

docassemble/ALDashboard/data/questions/install_assembly_line.yml

This is just a rough first experiment. There are some fairly big changes.
First of all, I should note that the installation interview sets github "token" not "password" and al_general.py asks for "password". Regardless of merging this in, that needs to be fixed either in here, similar to what I've done, or in al_general.py. I kept "token" around because I'm not sure if something else uses "token".
1. This is a fairly big UX departure from the previous version. Let me know if you want to try to revert a bit - keep it all on the same page or other such constraints. This change makes it a departure from the flow of the rest of the interview. The biggest departure being an in-flow review screen for just the GitHub details.
2. I also changed how token input is being taken and used, but I can …

Clarify GitHub auth setup instructions for feedback and "last updated"

---

docassemble/ALDashboard/aldashboard.py
docassemble/ALDashboard/data/questions/install_assembly_line.yml
setup.py

#41 broke the GitHub questions up. This enhances that by checking that the GitHub token is valid and has valid scopes, then using the token to get the username instead of asking the user for it.
On the topic of permissions, I've confirmed from [a July 20 community post](https://github.community/t/what-permission-level-do-i-need-to-create-issues-using-pat/124769/2) that `repo` or `public_repo` permission scopes are the minimal requirements for what we need. Suffolk uses `public_repo`, so the code accepts both of those, though the question doesn't explain that. I think that explanation would be a lot on top of everything else. We can try to find a way if desired.
Also, I wasn't sure if we also want to allow other scopes (broader ones) that also allow issue filing. In case we want that, I've …

Add to #41 by validating github auth with error screens for the user

---

docassemble/ALDashboard/data/questions/install_assembly_line.yml

This lets a new AssemblyLine user proceed with install even if they have not yet obtained any API keys
Fix #52

Make API configuration an optional step, clean up visual noise on config page for APIs

---

docassemble/ALDashboard/aldashboard.py
docassemble/ALDashboard/data/questions/install_packages.yml
docassemble/ALDashboard/data/questions/update_packages.yml

Remove dependency on API key for package install and update dashboards.
Also--add the dispatch directives to the config instead of making author copy and paste.
Fix #58 
Fix #34

Update and install packages without requiring an API key

---

docassemble/ALDashboard/data/questions/review_screen_generator.yml

Existing code runs into an error if the usage of fields | code doesn't match a pattern like x..._fields()

Handle more unusual fields | code usage

---

docassemble/ALDashboard/aldashboard.py
docassemble/ALDashboard/data/questions/manage_users.yml

sqlalchemy sometimes returns tuples where it would default return dicts. Decided to change the frontend to use tuples instead of dicts, since ALDashboard isn't built for people to overwrite.
Fix #77.

Fix sqlalchemy bug

---

docassemble/ALDashboard/data/questions/compile_bootstrap.yml

The version of node needs to be at least v14. That comes with docassemble-os >= 1.4.43.
Also, use content-disposition: attachment instead of requiring right click | save link as, and offer a way to download the SCSS file which ideally would be maintained in the source repository.

Upgrade Bootstrap in theme compiler to v5.2.3

---

docassemble/ALDashboard/create_package.py

The deprecation warning from pip:
```
UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
```
Side note: I believe that "future version" date is now 2023-09-26, a month from now. So I'll likely do a few smaller changes in all of the repos that need this change soon.  
Similar change to https://github.com/jhpyle/docassemble/pull/640.

Correct description-file to description_file

---

docassemble/ALDashboard/aldashboard.py
docassemble/ALDashboard/data/questions/list_sessions.yml

Made a few small fixes to the `list_sessions.yml` interview after using it this morning:
* The interviews were listed all out of order, which made it hard to know where to start looking: they are now sorted alphabetically
* `speedy_get_users` returned Tuples, which didn't seem to be working in the user selection on the first screen of `list_sessions`, and I don't think DA handles very well in general. I changed it to return a List of key-value maps, which is what the `code` section of a combobox expects.
Tested both of these changes in apps-dev, and it works great. Might merge these soon, since I've trying to use it to pinpoint more production errors with the ALAffidavitOfIndigency that are appearing.

Sort sessions and fix users dropdown

---

docassemble/ALDashboard/data/questions/compile_bootstrap.yml
docassemble/ALDashboard/data/questions/menu.yml

Correcting a mistake I made a while back; the default colors are horrible. I probably made them for testing and never changed them back. It is a problem because it's impossible to tell what the colors will be before generating the theme, and it's not clear what those values are by default in docassemble.
Now, the default colors when you are typing the theme are the same ones from docassemble's base theme. So you'll get what you expect.
Also shortened a the bootstrap interview label from the menu, which was too long.

Better Bootstrap theme default

---

docassemble/ALDashboard/data/questions/compile_bootstrap.yml
docassemble/ALDashboard/data/questions/pdf_wrangling.yml
docassemble/ALDashboard/data/static/test_html.html

Mostly pure HTML from https://bootswatch.com/default/ in `test_html.html`, and using a trick from https://stackoverflow.com/a/13883978/11416267 to add the generated theme to the CSS of the page using Javascript. Works great, might want to consider culling down some of the things shown to be just the docassemble components, since there's a whole lot, and most of it, people won't have to worry about.
The only thing is that there's some extra margin on each component in bootswatch that we don't have. Can add it if we think things aren't readable, but it didn't make too much of a different to me so I avoided adding too much custom css for just this page.
Fixes #11.

Show preview of what the theme will look like

---

README.md

Not sure if this is desired here or the right place for it, but it's what I was looking for in this location. 
Perhaps also an explanation for how to run the Dashboard without adding it to the menu / how to format the link could be helpful here.

Add instructions for how to add Dashboard to drop down to README.md

---

docassemble/ALDashboard/data/questions/pdf_wrangling.yml

To confirm that you renamed the correct fields, which can be difficult for longer PDFs.
I stuck with the same placement of the PDF, with a new title to show it's the new field names.
(Another quick proof of concept, feel free to reject if we think we should improve the problem in a different way.)

Show a preview of the PDF labels when Renaming

---

docassemble/ALDashboard/data/questions/review_screen_generator.yml

Went through the review screen generator for one of my new interviews, and it was super great, literally saved me hours.
There were a few easy improvements that I thought I'd make before I start documenting how to use the tool. They were fairly specific to my interview, but seem like good general improvements. I split out each into it's own commit, I suggest navigating like that.
The only one I was unsure if it was wanted was https://github.com/SuffolkLITLab/docassemble-ALDashboard/commit/387a55fdf908b61387b01ef7a0acb045620292b3, which adds something like 
```yml
event: review_intro
code: review_form
---
event: review_prior_case
code: review_form
...
```
for every section in the interview. Happy to remove that if we don't think it's a good way to organize sections in an interview by …

Review gen improvements

---

docassemble/ALDashboard/data/questions/menu.yml

`browse_feedback_sessions.yml` is now a button on the menu.
Fix #114.

Added link to Github Feedback interview

---

docassemble/ALDashboard/data/questions/docx_wrangling.yml
docassemble/ALDashboard/data/questions/menu.yml
docassemble/ALDashboard/docx_wrangling.py
docassemble/ALDashboard/requirements.txt
pyproject.toml
setup.py

This feature allows you to upload a DOCX file and assign it draft labels via OpenAI's GPT-4-turbo API. An API key must be present in the global configuration under the setting `openai api key`.
The draft labels can be reviewed and edited before saving the DOCX.

Add an MVP feature that lets you automatically add labels to a DOCX file with OpenAI

---

docassemble/ALDashboard/data/questions/review_screen_generator.yml

* Named it "AL Review Generator" so I can be consistent in the documentation. The only place it appears is in the nav bar, and happy to change it to whatever we want, as long at it's not "Assembly Line Review Screen Generator Tool", lol
* Fixed issue w/ fields using `label` and `field` attributes
* Fixed bug with `<strong>` being on the same lines as mako
* Wraps fields that were `show if`d on their question with a `if showifdef` in the button text.
Also related to https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/388

More improvements to the Review generator

---

docassemble/ALDashboard/data/questions/compile_bootstrap.yml

It's needed for the right version of node to be installed.
Didn't have time to dive into directly comparing versions, but this is better than talking about a niche DA concept with no reference to the docs.

Show the system version on the Bootstrap screen

---

docassemble/ALDashboard/data/questions/review_screen_generator.yml

Some spare code that was on my machine, that skips making tables for ALPeopleLists. I had intended on waiting until https://github.com/SuffolkLITLab/docassemble-AssemblyLine/commit/3d0181df9f2c78a87db86e018825cffaf8ce27c4 (the commit in Assembly Line with default people tables) was released (that was merged Dec 16th, last release was the 4th, so it hasn't been yet), before adding this to the Dashboard. Tested a little bit with MLH interviews, but not thoroughly.

Skip over ALPeople in review generator

---

docassemble/ALDashboard/aldashboard.py
docassemble/ALDashboard/data/questions/list_sessions.yml
docassemble/ALDashboard/data/questions/manage_answer_viewers.yml
docassemble/ALDashboard/data/questions/menu.yml

Fix #136
Fix #135 
This PR adds the ability for any authorized role on the system to view sessions belonging to a particular interview. E.g, the Appeals Court clerk can log in and view answers for the interviews they manage and control, without having the ability to see sessions for Trial Court documents.
It also has some small enhancements to the interview list feature:
1. We show metadata like title and progress, for Assembly Line interviews that added JSON metadata
2. We show the user's name and email, not just their ID
3. We let admins delete sessions
I think this could be a nice model for adding additional features that interact with the global configuration, with a simple frontend.
This is getting to a more general purpose dashboard for managing user sessions with this release.

Improvements to view answer dashboard - allow sharing on a per-interview basis, show more detail, and allow deleting sessions

---

docassemble/ALDashboard/aldashboard.py
docassemble/ALDashboard/data/questions/browse_interviews.yml
docassemble/ALDashboard/data/questions/install_assembly_line.yml
docassemble/ALDashboard/data/questions/install_packages.yml
docassemble/ALDashboard/data/questions/menu.yml
docassemble/ALDashboard/package_scanner.py
docassemble/ALDashboard/requirements.txt
docassemble/ALDashboard/translation.py
pyproject.toml

Fix #119 
Fix #64 
Adds a simple dashboard to let you view installed packages and the YAML files in them, and then run those packages. Makes it unnecessary to create a link to run the package.
Also adds the ability to add a private access token to the global configuration and to use a private access token when installing a package from GitHub using the Dashboard.

Improvements to package install and browsing

---

docassemble/ALDashboard/data/questions/review_screen_generator.yml

This gets it to work with https://github.com/jhpyle/docassemble/blob/master/docassemble_demo/docassemble/demo/data/questions/questions.yml

Skip a fields statement if it is a dictionary instead of a list in the review generator

---

docassemble/ALDashboard/aldashboard.py

Previously had the error:
```
Error in assembly: AttributeError: 'bytes' object has no attribute 'fileno'
...
File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/ALDashboard/aldashboard.py", line 353, in list_installed_fonts\n    output = subprocess.run(\n', '
File "/usr/lib/python3.10/subprocess.py", line 1606, in _get_handles\n    p2cread = stdin.fileno()\n
```
Not sure what really changed between versions, but we can make the first call to `fc-list` act the same as the call to text (i.e. pass `text=True`) to make it a string and not bytes.
The subprocess docs
(https://docs.python.org/3/library/subprocess.html#subprocess.run) say that you should use the `input` argument for strings, which also fixes the internal error in subprocess, which seems to be …

Fix font listing

---

.github/workflows/deploy.yml

Grabbed this bit from the GitHub templates for pages sites, i.e. https://github.com/SuffolkLITLab/EfileProxyServer/blob/main/.github/workflows/docs_site.yml

Only allow one concurrent deployment to Dev

---

docassemble/ALDashboard/aldashboard.py
docassemble/ALDashboard/data/questions/file_index.yml
docassemble/ALDashboard/data/questions/menu.yml

On botched DA upgrades, docassemble very often will use a lower file number index than it should. When it does, there's a risk of leaking user information to other unsuspecting users.
From @nonprofittechy:
> This adds a new dashboard icon that lets you view the current next file ID that will be assigned, compare it to the most recent file ID that is in use on S3, warn you if the database ID is too low relative to the most recent file, and choose a number to increment the most recent file ID by.
Split off of #158.
Tested just this branch on apps-dev, works well for me.

Dashboard panel to fix file upload index issues
